apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-provider
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-provider
spec:
  progressDeadlineSeconds: 2147483647
  replicas: {{ .Values.replicaCount | default 1 }}
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: {{ .Release.Name }}-provider
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-provider
    spec:
      containers:
        - name: provider
          image: {{ .Values.image.repository | default "oceanprotocol/provider-py" }}:{{ .Values.image.tag | default "latest" }}{{ if .Values.image.digest }}@{{ .Values.image.digest }}{{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" | quote }}
          env:
            - name: ARTIFACTS_PATH
              value: /ocean-provider/artifacts
            - name: NETWORK_URL
              value: |
                {"100":"https://rpc.genx.minimal-gaia-x.eu"}
            - name: PROVIDER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-keys
                  key: privateProviders
            - name: UNIVERSAL_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-keys
                  key: privateOperator
            - name: LOG_LEVEL
              value: DEBUG
            - name: OCEAN_PROVIDER_URL
              value: "http://0.0.0.0:8030"
            - name: OCEAN_PROVIDER_WORKERS
              value: "4"
            - name: IPFS_GATEWAY
              value: {{ .Values.ipfsGateway | default ( printf "http://%s-ipfs.%s" .Release.Name .Release.Namespace ) | quote }}
            - name: OCEAN_PROVIDER_TIMEOUT
              value: "9000"
            - name: OPERATOR_SERVICE_URL
              value: {{ .Values.operatorAPI | default ( printf "http://%s-operator-api.%s:8050" .Release.Name .Release.Namespace ) | quote }}
            - name: AQUARIUS_URL
              value: "https://aquarius510.v4.delta-dao.com"
            - name: REQUEST_TIMEOUT
              value: "10"
            - name: PROVIDER_FEE_TOKEN
              value: {{ .Values.token | default "0x0995527d3473b3a98c471f1ed8787acd77fbf009" | quote }}
          ports:
            - containerPort: 8030
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 700Mi
            requests:
              cpu: 500m
              memory: 700Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
