# Default values for provider.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

networks:
  networksURL:
  publicProviders:
  privateProviders:
  publicOperator:
  privateOperator:

ipfs:
  replicaCount:
  image:
    repository: ""
    tag: ""
    digest: ""
    pullPolicy: ""
  storage:
    classname: ""
    access: ""
    size: ""
  ingress:
    enabled: true
    annotations: {}
    tls: false
    classname: ""
    host: ""
    secretName: ""

postgres:
  replicaCount:
  image:
    repository: ""
    tag: ""
    digest: ""
    pullPolicy: ""
  db:
    name: ""
    user: ""
    pass: ""
    host: ""
    port: ""
    path: ""
    mountPath: ""
  storage:
    classname: ""
    access: ""
    size: ""

provider:
  replicaCount:
  image:
    repository: ""
    tag: ""
    digest: ""
    pullPolicy: ""
  ipfsGateway: ""
  operatorAPI: ""
  providerFeeToken: ""
  aquariusURL: ""
  # Extra environment variables to be added to the provider container
  extraEnv: []
    # - name: CUSTOM_ENV_VAR
    #   value: "custom_value"
    # - name: SECRET_ENV_VAR
    #   valueFrom:
    #     secretKeyRef:
    #       name: my-secret
    #       key: secret-key
  # Extra environment variables from ConfigMaps
  extraEnvFrom: []
    # - configMapRef:
    #     name: my-configmap
    # - secretRef:
    #     name: my-secret
  # Extra ConfigMaps to mount as volumes
  extraConfigMaps: []
    # - name: my-configmap
    #   mountPath: /path/to/mount
    #   readOnly: true
  # Extra Secrets to mount as volumes
  extraSecrets: []
    # - name: my-secret
    #   mountPath: /path/to/mount
    #   readOnly: true
  ingress:
    enabled: true
    annotations: {}
    tls: false
    classname: ""
    host: ""
    secretName: ""

operator-api:
  replicaCount:
  image:
    repository: ""
    tag: ""
    digest: ""
    pullPolicy: ""
