apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-provider
  namespace: {{ .Release.Namespace }}
data:
  privateOperator: {{ .Values.privateOperator | required "The Provider private operator key is required!" | b64enc }}
  POSTGRES_DB: {{ .Values.db.name | default "postgresdb" | b64enc }}
  POSTGRES_USER: {{ .Values.db.user | default "postgresadmin" | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.db.pass | default "postgresadminpass" | b64enc }}
  POSTGRES_HOST: {{ .Values.db.host | default ( printf "%s-postgres.%s" .Values.providerReleaseName .Values.providerNamespace ) | b64enc }}
  POSTGRES_PORT: {{ .Values.db.port | default "5432" | b64enc }}
